### ISSUE TITLE
```/api/_advices.ts``` wrong author 

### ISSUE THREAD

**Issue by park-minhyeong** [gwongibeom/korean-advice-open-api#3]
<img width="844" alt="image" src="https://github.com/user-attachments/assets/6637a665-10b3-44c5-b149-f00e83e9179d">

**Comment by gwongibeom** [comment]
기여해보시죠!

**Comment by gwongibeom** [comment]
@maldron0309 @park-minhyeong 랜덤 한국어 명언 API에 기여해주셔서 감사합니다.
